### ISSUE TITLE
Remove broken symlinks on a catkin clean

### ISSUE THREAD

**Issue by SomeshDaga** [pyros-dev/catkin_pip#207]
Upon building a package with `catkin_pip`, the `devel/etc/catkin/profile.d/42.site_packages.sh` symlink is created in the workspace's devel space.

The symlink however remains on doing a `catkin clean <PKG>`, but no longer points to a valid resource.

On attempting to rebuild the package, the following error is seen:

```
Traceback (most recent call last):
  File "/usr/bin/catkin", line 9, in <module>
    load_entry_point('catkin-tools==0.4.4', 'console_scripts', 'catkin')()
  File "/usr/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 267, in main
    catkin_main(sysargs)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 262, in catkin_main
    sys.exit(args.main(args) or 0)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/cli.py", line 290, in main
    ctx = Context.load(opts.workspace, opts.profile, opts, append=True)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/context.py", line 175, in load
    ctx.load_env()
  File "/usr/lib/python2.7/dist-packages/catkin_tools/context.py", line 324, in load_env
    sticky_env = get_resultspace_environment(self.devel_space_abs, quiet=True)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/resultspace.py", line 69, in get_resultspace_environment
    for path in os.listdir(env_hooks_path)]
IOError: [Errno 2] No such file or directory: '<CATKIN_WORKSPACE>/devel/etc/catkin/profile.d/42.site_packages.sh'
```

**Comment by asmodehn** [comment]
Thanks for posting this issue !
Indeed cleaning is an important step that never receive enough love and care :-)

I probably will not have any time to work on this soon, so feel free to post a PR whenever you can. Thanks !
