### ISSUE TITLE
using install workspace before creation by catkin

### ISSUE THREAD

**Issue by asmodehn** [pyros-dev/catkin_pip#9]
We write the catkin-pip-setup.cmake script into the install workspace before the workspace is even created by catkin.
This can have unexpected effect (permissions error, etc. )

We should write the script in install workspace only after catkin creates it (during `make install` call).
This means we need to use `build/` directory to keep the script that will create it ( and not sue the script from source for that... ).
Maybe we should follow catkin strategy a bit more closely ?
Or maybe even become more bare cmake compatible, to rely less on catkin ?

**Comment by asmodehn** [comment]
Additionally this creates problem when building on the buildfarm : 

```
See <http://build.ros.org/job/Ibin_uT64__pyros_setup__ubuntu_trusty_amd64__binary/8/>

------------------------------------------
[...truncated 2376 lines...]
Hit http://archive.ubuntu.com trusty-security/main amd64 Packages
Hit http://archive.ubuntu.com trusty-security/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty-security/universe amd64 Packages
Hit http://archive.ubuntu.com trusty/main Sources
Hit http://archive.ubuntu.com trusty/restricted Sources
Hit http://archive.ubuntu.com trusty/universe Sources
Hit http://archive.ubuntu.com trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty/universe amd64 Packages
Reading package lists...
Invoking 'apt-get install -q -y -o Debug::pkgProblemResolver=yes ros-indigo-rostest'
Reading package lists...
Building dependency tree...
Reading state information...
Starting pkgProblemResolver with broken count: 0
Starting 2 pkgProblemResolver with broken count: 0
Done
The following NEW packages will be installed:
  ros-indigo-rostest
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 26.9 kB of archives.
After this operation, 187 kB of additional disk space will be used.
Get:1 http://repositories.ros.org/ubuntu/building/ trusty/main ros-indigo-rostest amd64 1.11.19-0trusty-20160420-012507-0700 [26.9 kB]
Fetched 26.9 kB in 0s (0 B/s)
Selecting previously unselected package ros-indigo-rostest.
(Reading database ... 39992 files and directories currently installed.)
Preparing to unpack .../ros-indigo-rostest_1.11.19-0trusty-20160420-012507-0700_amd64.deb ...
Unpacking ros-indigo-rostest (1.11.19-0trusty-20160420-012507-0700) ...
Setting up ros-indigo-rostest (1.11.19-0trusty-20160420-012507-0700) ...
 ---> 43601380e1bd
Removing intermediate container 173a789d548f
Step 35 : RUN echo "ros-indigo-rosunit: 1.11.12-0trusty-20160321-181855-0700" && python3 -u /tmp/wrapper_scripts/apt-get.py update-and-install -q -y -o Debug::pkgProblemResolver=yes ros-indigo-rosunit
 ---> Running in b960ebaba86b
ros-indigo-rosunit: 1.11.12-0trusty-20160321-181855-0700
Invoking 'apt-get update'
Hit http://repositories.ros.org trusty InRelease
Ign http://archive.ubuntu.com trusty InRelease
Hit http://archive.ubuntu.com trusty-updates InRelease
Hit http://archive.ubuntu.com trusty-security InRelease
Hit http://repositories.ros.org trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty Release.gpg
Hit http://archive.ubuntu.com trusty-updates/main Sources
Hit http://archive.ubuntu.com trusty-updates/restricted Sources
Hit http://archive.ubuntu.com trusty-updates/universe Sources
Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages
Hit http://archive.ubuntu.com trusty Release
Hit http://archive.ubuntu.com trusty-security/main Sources
Hit http://archive.ubuntu.com trusty-security/restricted Sources
Hit http://archive.ubuntu.com trusty-security/universe Sources
Hit http://archive.ubuntu.com trusty-security/main amd64 Packages
Hit http://archive.ubuntu.com trusty-security/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty-security/universe amd64 Packages
Hit http://archive.ubuntu.com trusty/main Sources
Hit http://archive.ubuntu.com trusty/restricted Sources
Hit http://archive.ubuntu.com trusty/universe Sources
Hit http://archive.ubuntu.com trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty/universe amd64 Packages
Reading package lists...
Invoking 'apt-get install -q -y -o Debug::pkgProblemResolver=yes ros-indigo-rosunit'
Reading package lists...
Building dependency tree...
Reading state information...
Starting pkgProblemResolver with broken count: 0
Starting 2 pkgProblemResolver with broken count: 0
Done
ros-indigo-rosunit is already the newest version.
ros-indigo-rosunit set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
 ---> afbf2c2791ae
Removing intermediate container b960ebaba86b
Step 36 : USER buildfarm
 ---> Running in b7a1241ee373
 ---> 5f02c8a392ea
Removing intermediate container b7a1241ee373
Step 37 : ENTRYPOINT sh -c
 ---> Running in 349c828f6320
 ---> f039599c8ebd
Removing intermediate container 349c828f6320
Step 38 : CMD PYTHONPATH=/tmp/ros_buildfarm:$PYTHONPATH PATH=/usr/lib/ccache:$PATH python3 -u /tmp/ros_buildfarm/scripts/release/build_binarydeb.py indigo pyros_setup --sourcedeb-dir /tmp/binarydeb
 ---> Running in 71018acaaaab
 ---> 328f6a9df022
Removing intermediate container 71018acaaaab
Successfully built 328f6a9df022
+ echo # END SECTION
# END SECTION
+ echo # BEGIN SECTION: Run Dockerfile - build binarydeb
# BEGIN SECTION: Run Dockerfile - build binarydeb
+ docker run --rm --cidfile=<http://build.ros.org/job/Ibin_uT64__pyros_setup__ubuntu_trusty_amd64__binary/ws/docker_build_binarydeb/docker.cid> -e=HOME= --net=host -v <http://build.ros.org/job/Ibin_uT64__pyros_setup__ubuntu_trusty_amd64__binary/ws/ros_buildfarm>:/tmp/ros_buildfarm:ro -v <http://build.ros.org/job/Ibin_uT64__pyros_setup__ubuntu_trusty_amd64__binary/ws/binarydeb>:/tmp/binarydeb -v /home/jenkins-slave/.ccache:/home/buildfarm/.ccache binarydeb_build.indigo_ubuntu_trusty_amd64_pyros_setup
# BEGIN SUBSECTION: build binarydeb
Package 'ros-indigo-pyros-setup' version: 0.1.0-0trusty-20160510-014513-0700
Invoking 'apt-src build ros-indigo-pyros-setup' in '/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0'
I: Building in /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0 ..
dpkg-buildpackage: source package ros-indigo-pyros-setup
dpkg-buildpackage: source version 0.1.0-0trusty-20160510-014513-0700
dpkg-buildpackage: source distribution trusty
dpkg-buildpackage: source changed by AlexV <asmodehn@gmail.com>
 dpkg-source --before-build ros-indigo-pyros-setup-0.1.0
dpkg-buildpackage: host architecture amd64
 fakeroot debian/rules clean
dh  clean
   dh_testdir
   dh_auto_clean
Unknown option: buildsystem
dh_testdir: warning: ignored unknown options in DH_OPTIONS
   dh_clean
        rm -f debian/ros-indigo-pyros-setup.substvars
        rm -f debian/ros-indigo-pyros-setup.*.debhelper
        rm -rf debian/ros-indigo-pyros-setup/
        rm -f debian/*.debhelper.log
        rm -f debian/files
        find .  \( \( -type f -a \
                \( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
                 -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
                 -o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
                 -o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
                \) -exec rm -f {} + \) -o \
                \( -type d -a -name autom4te.cache -prune -exec rm -rf {} + \) \)
        rm -f *-stamp
dh  build
Unknown option: buildsystem
dh_clean: warning: ignored unknown options in DH_OPTIONS
 debian/rules build
   dh_testdir
   debian/rules override_dh_auto_configure
make[1]: Entering directory `/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0'
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi && \
        dh_auto_configure -- \
                -DCATKIN_BUILD_BINARY_PACKAGE="1" \
                -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
                -DCMAKE_PREFIX_PATH="/opt/ros/indigo"
Unknown option: buildsystem
dh_testdir: warning: ignored unknown options in DH_OPTIONS
        mkdir -p obj-x86_64-linux-gnu
        cd obj-x86_64-linux-gnu
        cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCATKIN_BUILD_BINARY_PACKAGE=1 -DCMAKE_INSTALL_PREFIX=/opt/ros/indigo -DCMAKE_PREFIX_PATH=/opt/ros/indigo
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/x86_64-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/x86_64-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/x86_64-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/x86_64-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Using CATKIN_DEVEL_PREFIX: /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
-- Found PythonInterp: /usr/bin/python (found version "2.7.6")
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Skip enable_testing() when building binary package
-- Using CATKIN_TEST_RESULTS_DIR: /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/test_results
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.18
-- Loading catkin-pip.cmake from /opt/ros/indigo/share/catkin_pure_python/cmake...
CMake Error: Could not open file for write in copy operation /opt/ros/indigo/.catkin-pip-setup.cmake.tmp-- Loading /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/devel/.catkin-pip-setup.cmake...
-- Catkin pip PYTHONPATH : /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/devel/lib/python2.7/site-packages:/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/devel/lib/python2.7/dist-packages:/opt/ros/indigo/lib/python2.7/dist-packages:/tmp/ros_buildfarm:
-- Catkin pip PATH : /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/devel/bin:/opt/ros/indigo/bin:/usr/lib/ccache:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
--     ... Catkin pip was not found in /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/devel/bin ...
--     ... Retrieving catkin_pure_python requirements using system pip ...

CMake Error: : System Error: Permission denied
CMake Error at /opt/ros/indigo/share/catkin_pure_python/cmake/catkin-pip.cmake:18 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  /opt/ros/indigo/share/catkin_pure_python/cmake/catkin_pure_pythonConfig.cmake:190 (include)
  /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:76 (find_package)
  CMakeLists.txt:11 (find_package)


--     ... Done ... [0]:
--     ... Running python -m pip install -r /opt/ros/indigo/share/catkin_pure_python/cmake/catkin-pip-fixups.req --ignore-installed --src /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0 --exists-action b --prefix /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/devel ...
--     ... Done ... [0]: Collecting pip (from -r /opt/ros/indigo/share/catkin_pure_python/cmake/catkin-pip-base.req (line 3))
  Downloading pip-8.1.1-py2.py3-none-any.whl (1.2MB)
Collecting setuptools (from -r /opt/ros/indigo/share/catkin_pure_python/cmake/catkin-pip-base.req (line 4))
  Downloading setuptools-21.0.0-py2.py3-none-any.whl (509kB)
Collecting nose (from -r /opt/ros/indigo/share/catkin_pure_python/cmake/catkin-pip-fixups.req (line 7))
  Downloading nose-1.3.7-py2-none-any.whl (154kB)
Installing collected packages: pip, setuptools, nose
Successfully installed nose-1.3.7 pip-8.1.1 setuptools-21.0.0

-- Found catkin_pure_python pip command at /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/devel/bin/pip.
-- Found catkin_pure_python nosetests command at /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/devel/bin/nosetests.
--     ... Running /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/devel/bin/pip install -r /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/requirements.txt --ignore-installed --src /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0 --exists-action b --prefix /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/devel ...
--     ... Done ... [0]: Collecting nose>=1.3.7 (from -r /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/requirements.txt (line 4))
  Using cached nose-1.3.7-py2-none-any.whl
Installing collected packages: nose
Successfully installed nose-1.3.7

--     ... Running /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/devel/bin/pip install -e . --prefix /tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/devel ...
--     ... Done ... [0]: Obtaining file:///tmp/binarydeb/ros-indigo-pyros-setup-0.1.0
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from pyros-setup==0.1.0)
Collecting importlib (from pyros-setup==0.1.0)
  Downloading importlib-1.0.3.tar.gz
Building wheels for collected packages: importlib
  Running setup.py bdist_wheel for importlib: started
  Running setup.py bdist_wheel for importlib: finished with status 'done'
  Stored in directory: /home/buildfarm/.cache/pip/wheels/2a/04/fb/873fc6754f3d84f4ad1ee05bd2e63bc52dc883fbe314c5801a
Successfully built importlib
Installing collected packages: importlib, pyros-setup
  Running setup.py develop for pyros-setup
Successfully installed importlib-1.0.3 pyros-setup-0.1.0

-- Configuring incomplete, errors occurred!
See also "/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/CMakeFiles/CMakeOutput.log".
See also "/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0/obj-x86_64-linux-gnu/CMakeFiles/CMakeError.log".
dh_auto_configure: cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=None -DCATKIN_BUILD_BINARY_PACKAGE=1 -DCMAKE_INSTALL_PREFIX=/opt/ros/indigo -DCMAKE_PREFIX_PATH=/opt/ros/indigo returned exit code 1
make[1]: *** [override_dh_auto_configure] Error 2
make[1]: Leaving directory `/tmp/binarydeb/ros-indigo-pyros-setup-0.1.0'
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
E: Building failed
Traceback (most recent call last):
  File "/tmp/ros_buildfarm/ros_buildfarm/binarydeb_job.py", line 120, in build_binarydeb
    subprocess.check_call(cmd, cwd=source_dir)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['apt-src', 'build', 'ros-indigo-pyros-setup']' returned non-zero exit status 1

--------------------------------------------------------------------------------------------------
`apt-src build ros-indigo-pyros-setup` failed.
This is usually because of an error building the package.
The traceback from this failure (just above) is printed for completeness, but you can ignore it.
You should look above `E: Building failed` in the build log for the actual cause of the failure.
--------------------------------------------------------------------------------------------------

# END SUBSECTION
Build step 'Execute shell' marked build as failure
[ssh-agent] Stopped.
[description-setter] Could not determine description.
```

**Comment by asmodehn** [comment]
This has been fixed. we are now using the CMAKE_BINARY_PATH to store things for later install.
